export const data = [
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '응시',
  },
  {
    name: '홍길동',
    email: 'hong@gmail.com',
    department: '기계공학과',
    id: '2014965038',
    status: '미응시',
  },
];
